# Generated by Django 5.1.3 on 2024-12-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturenote',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
